# Config virtual machine info
machine_name : 'LAMP Vagrant'
local_domain : 'lamp-vagrant.local'
private_ip   : '192.168.90.10'
machine_ram  : 'auto'
machine_cpu  : 'auto'

mysql_root_pass : 'root'
mysql_user      : 'lamp'
mysql_user_pass : 'lamp'
mysql_user_db   : 'lamp'

# Config Synced folders
syncDir :
  - host:  www
    guest: /var/www/html
    owner: vagrant
    group: www-data
    dmode: 775
    fmode: 775